import React from 'react'

const About = () => {
  return (
    <div>
      <div id="carouselExampleSlidesOnly" className="carousel slide" data-bs-ride="carousel">
        <div className="carousel-inner">
          <div className="carousel-item active">
            <h2 className="my-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, cumque!</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus, nihil ratione illo impedit labore minus dolore rerum in hic asperiores tempore quae sed distinctio, dicta totam recusandae reiciendis rem assumenda animi nulla atque? Aspernatur quod repellendus, sint ducimus cupiditate animi maiores quibusdam quisquam exercitationem nobis pariatur, optio ad eligendi doloremque unde maxime ea similique repellat sit dolores quia dolor quo consequuntur harum? Commodi provident vel deleniti eius quam ducimus enim nulla aut? Quos unde saepe corrupti illum fugiat, rerum sed eaque? Velit, voluptatum magni eligendi, tempore laudantium suscipit ducimus itaque voluptatibus ipsam temporibus commodi qui vitae fugiat recusandae quidem. Quo provident consequuntur, similique tempore distinctio maiores expedita corporis ipsam autem architecto labore voluptates eius culpa aliquid ipsum delectus aliquam neque. Fugiat minus illo repudiandae dolores, sunt id dolore voluptas eos veritatis. Commodi odio neque rerum, veritatis beatae laboriosam mollitia reiciendis. Sit molestias voluptatum nulla, recusandae alias facilis qui sunt doloremque maxime dignissimos. Ullam similique vero magnam velit sapiente doloribus maiores eaque modi hic, quas nisi itaque impedit ex quae nihil nulla exercitationem consequatur dolor iure aliquam. Necessitatibus dolores eum dignissimos deserunt? A cumque sed praesentium, eligendi vitae, accusamus maiores necessitatibus doloribus cupiditate provident nihil tempora consequatur placeat consectetur enim similique.</p>
          </div>
          <div className="carousel-item">
            <h2 className="my-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, cumque!</h2>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quidem consectetur expedita nam inventore consequuntur nihil repellendus ipsum officiis dolores? Quis ratione eveniet itaque eligendi, ut odit, nemo hic magnam aperiam quas dicta ad quae laudantium voluptas labore vitae, dignissimos distinctio iure ea laborum facilis optio. Veniam possimus nihil enim? Voluptate, unde voluptatum. Eveniet est assumenda dolores quos veniam, iusto laudantium quam nam reprehenderit atque ex optio repudiandae asperiores cumque dolor magni sunt eum dignissimos quisquam voluptatum harum saepe corporis? Quaerat quidem quibusdam culpa sit eveniet sequi non commodi ipsa modi. Aliquid recusandae, fugiat impedit delectus velit iusto similique aspernatur accusantium, minus vero soluta voluptas nam. Et velit iure vero impedit eligendi, voluptate amet soluta modi corporis, in totam, accusantium a sapiente unde dolorem quasi. Quisquam incidunt cumque, qui ipsa enim tempora autem eaque quos voluptatibus non. Nulla ducimus maxime quod? Expedita, animi architecto, maiores incidunt deserunt molestiae aspernatur quo eum quidem laboriosam aperiam sint, qui totam aliquid necessitatibus perferendis quisquam omnis! Soluta nostrum et facere consequatur recusandae nisi similique maiores. Ab, totam fugit sint architecto suscipit vitae? Perspiciatis at dicta quam eum alias quasi quis soluta expedita ipsam pariatur repudiandae modi quae, maxime mollitia, ratione provident qui unde rem iure!</p>
          </div>
          <div className="carousel-item">
            <h2 className="my-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, cumque!</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem ratione dolor aut ipsa eveniet facere eaque, repudiandae natus libero laboriosam tenetur dignissimos voluptate laborum ullam esse odit perferendis totam pariatur. Ex dicta provident, officia illo inventore rerum perferendis non? Inventore possimus pariatur natus. Architecto illum nemo dolorum animi, facere quibusdam tempore cumque quisquam, corrupti laboriosam blanditiis quia repellendus provident. Culpa ullam eius hic animi inventore officia laboriosam, quos nulla, tempora nostrum perspiciatis ex. Architecto, dicta in. Repudiandae asperiores ratione dolore sint non. Eligendi illo dolores in eaque libero asperiores beatae repudiandae perferendis voluptatum, doloremque aut omnis architecto nam perspiciatis quae hic distinctio esse voluptates praesentium dignissimos iste assumenda. Eligendi, quia nulla, debitis nemo nihil expedita maiores amet aperiam dicta vitae rem nisi odit, suscipit dolor magni eos provident repellendus ducimus beatae magnam autem quo odio ullam. Ducimus explicabo odit iusto expedita ad quaerat, error molestiae numquam at in facere illo totam asperiores, molestias minus praesentium ex id mollitia hic tempore quibusdam, doloribus ab est. Saepe itaque omnis aliquid quae labore corrupti exercitationem! Animi dolores tenetur aliquam nobis repudiandae ex, at dignissimos provident ipsa, maxime neque eligendi iusto? Veniam, ea voluptatum eligendi consectetur aliquam nesciunt suscipit voluptas neque voluptates deserunt. Voluptates.</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default About
